# Generated by Django 6.0.2 on 2026-02-19 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vocabulary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("czech", models.CharField(blank=True, max_length=100, null=True)),
                ("english", models.CharField(blank=True, max_length=100, null=True)),
                ("latin", models.CharField(blank=True, max_length=100, null=True)),
                ("german", models.CharField(blank=True, max_length=100, null=True)),
                ("slovak", models.CharField(blank=True, max_length=100, null=True)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "dictionary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="dictionary.dictionary",
                    ),
                ),
            ],
        ),
    ]
